optimize systemd

diff --git a/tools/systemd/profile/oceanbase-service.sh.template b/tools/systemd/profile/oceanbase-service.sh.template
--- a/tools/systemd/profile/oceanbase-service.sh.template
+++ b/tools/systemd/profile/oceanbase-service.sh.template
@@ -2,12 +2,14 @@
 
 DATE=`date '+%Y-%m-%d %H:%M:%S'`
 cnf_file='/etc/oceanbase.cnf'
-ip=`hostname -i`
+ip=`hostname -I | awk '/^[0-9]/ {print $1; exit}'`
 port=2886
 url="http://localhost"
 prefix=@CPACK_PACKAGING_INSTALL_PREFIX@
 unix_socket="$prefix/run/obshell.sock"
 obshell="$prefix/bin/obshell"
+etc_folder="$prefix/etc"
+current_user=`whoami`
 report=3
 
 function prepare_config_json {
@@ -44,6 +46,11 @@ function prepare_config_json {
   sed -i "s|HOSTIP|${ip}|g" $json_file
 }
 
+function prepare_env {
+  echo "change etc owner to ${current_user}"
+  chown $current_user:$current_user "${etc_folder}"
+}
+
 function do_reload_observer {
   echo "Not support reload now"
 }
@@ -73,8 +80,8 @@ function check_obagent_process {
         echo "obshell process with PID $pid is not running."
         $obshell admin start --ip $ip --port $port
         if [ $? -ne 0 ]; then
-          echo "start ob_agent failed"
-          exit
+          echo "start ob_shell failed"
+          exit 1
         fi
     fi
   else
@@ -104,10 +111,10 @@ function check_trace {
     state=$(echo "$response" | jq -r '.data.state')
     echo "the response state is $state"
     if [ "x$state" = "xSUCCEED" ]; then
-      echo "request successfully"
+      echo "$content request successfully"
       break
     elif [ "x$state" = "xFAILED" ]; then
-      echo "request failed"
+      echo "$content request failed"
       exit 1
     else
       count=$((count + 1))
@@ -124,8 +131,8 @@ function check_trace {
 function start_obshell {
   $obshell admin start --ip $ip --port $port > /dev/null 2>&1
   if [ $? -ne 0 ]; then
-    echo "start ob_agent failed"
-    exit
+    echo "start ob_shell failed"
+    exit 1
   fi
 }
 
@@ -170,19 +177,10 @@ function do_config_observer {
   check_trace $trace "config observer" 3 3
 }
 
-function deploy_observer {
-  echo "oceanbase service deployed at ${DATE}"
-  prepare_config_json
-  start_obshell
-  do_config_observer
-}
-
-function start_observer {
-  systemd-notify --ready
+function do_start_observer {
   # check observer status
   response=$(curl --silent -H "Content-Type: application/json" -X GET --unix-socket $unix_socket $url/api/v1/status)
   identity=$(echo "$response" | jq -r '.data.agent.identity')
-  systemd-notify "STATUS=Service is running"
   if [ "x$identity" = "xCLUSTER AGENT" ]; then
     echo "The observer is already bootstrap, please start it immediately"
     response=$(curl --silent -H "Content-Type: application/json" -X POST -d '{
@@ -223,39 +221,38 @@ function start_observer {
     echo "The observer has been installed before"
   fi
 
-  systemd-notify --status="Service is ready"
-
   if [ -f $prefix/run/observer.pid ]; then
     pid=$(cat $prefix/run/observer.pid)
-    while true; do
-        if [ ! -d "/proc/$pid" ]; then
-            echo "Observer process with PID $pid has exited."
-            break
-        fi
+    if [ ! -d "/proc/$pid" ]; then
+        echo "Observer process with PID $pid has exited."
+        break
+    fi
 
-        echo "Observer process with PID $pid is still running."
-        # check observer state
-        response=$(curl --silent -H "Content-Type: application/json" -X GET -d '{
-          "scope":
-            {
-              "type":"global",
-              "target":[]
-            },
-          "force": true
-          }' --unix-socket $unix_socket $url/api/v1/status)
-        ob_state=$(echo "$response" | jq -r '.data.obState')
-        if [ "x$ob_state" = "x1" ]; then
-            echo "The agent dose not know the observer password"
-            echo "1. Please set environment: export OB_ROOT_PASSWORD={root_passowrd}"
-            echo "2. Kill all the obshell process"
-            echo "3. Restart the agent process: $prefix/bin/obshell admin start --ip $ip --port $port"
-        fi
-        sleep 30
-    done
+    # check observer state
+    response=$(curl --silent -H "Content-Type: application/json" -X GET --unix-socket $unix_socket $url/api/v1/status)
+    ob_state=$(echo "$response" | jq -r '.data.obState')
+    if [ "x$ob_state" = "x1" ]; then
+        echo "The agent dose not know the observer password"
+        echo "1. Please set environment: export OB_ROOT_PASSWORD={root_passowrd}"
+        echo "2. Kill all the obshell process"
+        echo "3. Restart the agent process: $prefix/bin/obshell admin start --ip $ip --port $port"
+    fi
   else
     echo "observer PID file not found."
     exit 1
   fi
+}
+
+function start_observer {
+  /bin/bash $prefix/profile/telemetry.sh $report "10" >/dev/null 2>&1
+  prepare_config_json
+  prepare_env
+  if check_daemon_process; then
+    echo "The agent service is exist"
+  else
+    start_obshell
+  fi
+  do_start_observer
 }
 
 function stop_observer {
@@ -275,7 +272,6 @@ function stop_observer {
   fi
   trace=$(echo "$response" | jq -r '.data.id')
   check_trace $trace "stop observer" 20 6
-  systemd-notify --status='STOPPING=1'
 }
 
 function reload_observer {
@@ -286,15 +282,7 @@ function reload_observer {
 
 if [ "x$1" = "xstart" ]; then
   echo "oceanbase service started at ${DATE}"
-  /bin/bash $prefix/profile/telemetry.sh $report "10" >/dev/null 2>&1
-  prepare_config_json
-  if check_daemon_process; then
-    echo "The agent service is exist"
-  else
-    start_obshell
-  fi
   start_observer
-
 elif [ "x$1" = "xstop" ]; then
   echo "oceanbase service stopped at ${DATE}"
   stop_observer
@@ -307,7 +295,7 @@ elif [ "x$1" = "xdestroy" ]; then
   $obshell admin stop > /dev/null 2>&1
   if [ $? -ne 0 ]; then
     echo "stop obshell failed"
-    exit
+    exit 1
   fi
 fi
 
